name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 40
    strategy:
      matrix:
        include:
          - os: "linux"
            name: "ubuntu-1"
            runs-on: "ubuntu-18-04"
            # run-e2e: true
          - os: "mac"
            name: "arm64-1"
            runs-on: "mac-silicon"
          - os: "windows"
            name: "amd64-avx2-cuda-12-0"
            runs-on: "windows-cuda-12-0"

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3

      - name: Install make on Windows
        if: runner.os == 'windows'
        run: |
          choco install make -y

      - name: Install dependencies
        run: |
          make install-dependencies

      - name: Build engine 
        run: |
          make build-engine

      - name: Build example server
        run: |
          make build-example-server

      - name: Run e2e test
        run: |
          make run-e2e-test
